#!/usr/bin/env python3
"""moris_init.py — scaffold a new MORIS input deck in the Deck API v2 style.

Usage:
    python3 share/scripts/moris_init.py MyDeck [--dir DIR] [--force]

Emits DIR/MyDeck.cpp (a run-verified template: the immersed linear-elastic
sensitivity-sweep example, parameterized) plus DIR/README.md with the compile
and run recipe. Adapt the TODO(user) markers; the template compiles and runs
as-emitted.
"""

import argparse
import sys
from pathlib import Path

DECK_TEMPLATE = r"""/*
 * {name}.cpp — MORIS input deck (Deck API v2, generated by share/scripts/moris_init.py)
 *
 * Template: immersed linear-elastic plate cut by two design lines, with a
 * sweep-based finite-difference check of the shape sensitivities. Adapt the
 * sections marked TODO(user). Reference for the API: doc/internal/DECK_API_RFC.md;
 * worked example: projects/EXA/optimization/Shape_Sensitivity_Sweep_NewIO/.
 *
 * Compile+run (PyMORIS):   moris-run {name}.cpp --run-moris
 * Or in-tree:              share/scripts/create_shared_object.sh . build_opt {name}
 */

#include <string>
#include "moris_typedefs.hpp"
#include "cl_Matrix.hpp"
#include "linalg_typedefs.hpp"
#include "parameters.hpp"
#include "cl_Input_Deck.hpp"
#include "cl_Input_Deck_Vocabulary.hpp"
#include "fn_FEM_Presets.hpp"

namespace
{
    using namespace moris;

    // bulk phase 1 = material; phases 3 / 0 border the Dirichlet / Neumann interfaces
    const deck::Phase tMaterial( 1 );

    const std::string tMeshSets = tMaterial.bulk();                                     // HMR_dummy_n_p1,HMR_dummy_c_p1
    const std::string tDBCSets  = deck::interface( tMaterial, deck::Phase( 3 ) );       // iside_b0_1_b1_3
    const std::string tNBCSets  = deck::interface( tMaterial, deck::Phase( 0 ) );       // iside_b0_1_b1_0

    // FD in adjoint
    const real tFEMFdEpsilon = 1.0e-7;

    // FD step size in sweep
    const std::string tFDsweep = "1.0e-7";
}    // namespace

//------------------------------------------------------------------------------

MORIS_DECK( aDeck )
{
    using namespace moris;

    // ---- OPT: sweep-based FD verification of the shape sensitivities ------------
    auto& tOpt = aDeck.opt();
    tOpt.set( "is_optimization_problem", true );
    tOpt.set( "problem", "user_defined" );
    // NOTE: no 'library' parameter — the loaded deck is handed through to OPT

    tOpt( OPT::ALGORITHMS ).add_parameter_list( opt::Optimization_Algorithm_Type::SWEEP );
    tOpt.set( "hdf5_path", "{name}_sweep.hdf5" );
    tOpt.set( "evaluate_objective_gradients", true );
    tOpt.set( "evaluate_constraint_gradients", true );
    tOpt.set( "num_evaluations_per_adv", "1" );
    tOpt.set( "include_bounds", false );
    tOpt.set( "finite_difference_type", "all" );
    tOpt.set( "finite_difference_epsilons", tFDsweep );

    // objective and constraint as criteria expressions: values, criteria gradients,
    // GEN IQI_types order, and constraint types are all derived from the trees
    aDeck.objective( deck::criterion( "IQIBulkStrainEnergy" ) );
    aDeck.constraint( deck::criterion( "IQIBulkVolume" ) <= 0.0 );

    // ---- HMR: background mesh ----------------------------------------------------
    auto& tHmr = aDeck.hmr();
    tHmr.set( "number_of_elements_per_dimension", 2, 2 );
    tHmr.set( "domain_dimensions", 2.0, 2.0 );
    tHmr.set( "domain_offset", -1.0, -1.0 );
    tHmr.set( "lagrange_output_meshes", "0" );
    tHmr.set( "lagrange_orders", "1" );
    tHmr.set( "lagrange_pattern", "0" );
    tHmr.set( "bspline_orders", "1" );
    tHmr.set( "bspline_pattern", "0" );
    tHmr.set( "lagrange_to_bspline", "0" );
    tHmr.set( "refinement_buffer", 3 );
    tHmr.set( "staircase_buffer", 3 );
    tHmr.set( "adaptive_refinement_level", 1 );

    // ---- XTK: conformal cut ------------------------------------------------------
    auto& tXtk = aDeck.xtk();
    tXtk.set( "decompose", true );
    tXtk.set( "decomposition_type", "conformal" );
    tXtk.set( "enrich_mesh_indices", "0" );
    tXtk.set( "ghost_stab", true );
    tXtk.set( "multigrid", false );
    tXtk.set( "verbose", false );
    tXtk.set( "print_enriched_ig_mesh", false );
    tXtk.set( "exodus_output_XTK_ig_mesh", true );
    tXtk.set( "high_to_low_dbl_side_sets", true );

    // ---- GEN: two design lines -----------------------------------------------
    // (IQI_types is written automatically from the objective/constraint expressions)
    auto& tGen = aDeck.gen();

    // vertical line (x-position and normal are design variables)
    tGen( GEN::GEOMETRIES ).add_parameter_list( prm::create_level_set_geometry_parameter_list( gen::Field_Type::LINE ) );
    tGen.set( "center_x", 0.8, 0.8, 0.8 );
    tGen.set( "center_y", 0.3 );
    tGen.set( "normal_x", 1.0 );
    tGen.set( "normal_y", 0.0, 0.0, 0.0 );

    // oblique line
    tGen( GEN::GEOMETRIES ).add_parameter_list( prm::create_level_set_geometry_parameter_list( gen::Field_Type::LINE ) );
    tGen.set( "center_x", -0.6, -0.6, -0.6 );
    tGen.set( "center_y", -0.3, -0.3, -0.3 );
    tGen.set( "normal_x", 1.0, 1.0, 1.0 );
    tGen.set( "normal_y", 1.0, 1.0, 1.0 );

    // ---- FEM: linear elasticity via the preset -----------------------------------
    auto& tFem = aDeck.fem();
    tFem.hack_for_legacy_fem();

    fem::presets::Linear_Elastic_Config tElasticity;
    tElasticity.mBulkSets      = tMeshSets;
    tElasticity.mDirichletSets = tDBCSets;
    tElasticity.mNeumannSets   = tNBCSets;
    tElasticity.mTraction      = "0.0;0.1";
    fem::presets::linear_elastic( tFem, tElasticity );

    // displacement IQIs for the output mesh (raw parameter-list escape hatch)
    tFem( FEM::IQI ).add_parameter_list();
    tFem.set( "IQI_name", "IQIDispX" );
    tFem.set( "IQI_type", fem::IQI_Type::DOF );
    tFem.set( "dof_quantity", "UX,UY" );
    tFem.set( "leader_dof_dependencies", "UX,UY" );
    tFem.set( "vectorial_field_index", 0 );
    tFem.set( "mesh_set_names", tMeshSets );

    tFem( FEM::IQI ).add_parameter_list();
    tFem.set( "IQI_name", "IQIDispY" );
    tFem.set( "IQI_type", fem::IQI_Type::DOF );
    tFem.set( "dof_quantity", "UX,UY" );
    tFem.set( "leader_dof_dependencies", "UX,UY" );
    tFem.set( "vectorial_field_index", 1 );
    tFem.set( "mesh_set_names", tMeshSets );

    // FD scheme for the analytical sensitivity checks in FEM
    tFem( FEM::COMPUTATION );
    tFem.set( "finite_difference_scheme", fem::FDScheme_Type::POINT_3_CENTRAL );
    tFem.set( "finite_difference_perturbation_size", tFEMFdEpsilon );

    // ---- SOL: Belos + ILU, single static step, adjoint sensitivities ------------
    auto& tSol = aDeck.sol();
    tSol( SOL::LINEAR_ALGORITHMS ).add_parameter_list( sol::SolverType::BELOS_IMPL );
    tSol.set( "preconditioners", "0" );
    tSol( SOL::LINEAR_SOLVERS ).add_parameter_list();
    tSol( SOL::NONLINEAR_ALGORITHMS ).add_parameter_list();
    tSol( SOL::NONLINEAR_SOLVERS ).add_parameter_list();
    tSol.set( "NLA_DofTypes", "UX,UY" );
    tSol( SOL::TIME_SOLVER_ALGORITHMS ).add_parameter_list();
    tSol.set( "TSA_Num_Time_Steps", 1 );
    tSol.set( "TSA_Time_Frame", 1.0 );
    tSol( SOL::TIME_SOLVERS ).add_parameter_list();
    tSol.set( "TSA_DofTypes", "UX,UY" );
    tSol.set( "TSA_Output_Indices", "0" );
    tSol.set( "TSA_Output_Criteria", "Output_Criterion" );    // built-in always-true criterion
    tSol( SOL::SOLVER_WAREHOUSE ).set( "Sensitivity_Analysis_Type", sol::SensitivityAnalysisType::ADJOINT );
    tSol( SOL::PRECONDITIONERS ).add_parameter_list( sol::PreconditionerType::IFPACK );
    tSol.set( "ifpack_prec_type", "ILU" );

    // ---- MSI: defaults -----------------------------------------------------------
    aDeck.msi();

    // ---- VIS: displacement output ------------------------------------------------
    auto& tVis = aDeck.vis();
    tVis.set( "File_Name", std::pair< std::string, std::string >( "./", "{name}.exo" ) );
    tVis.set( "Mesh_Type", vis::VIS_Mesh_Type::STANDARD );
    tVis.set( "Set_Names", tMeshSets );
    tVis.set( "Field_Names", "UX,UY" );
    tVis.set( "Field_Type", "NODAL,NODAL" );
    tVis.set( "IQI_Names", "IQIDispX,IQIDispY" );
    tVis.set( "Save_Frequency", 1 );

    // ---- MORISGENERAL: defaults --------------------------------------------------
    aDeck.morisgeneral();
}
"""

README_TEMPLATE = """# {name}

Generated by `share/scripts/moris_init.py` (Deck API v2 — see
`doc/internal/DECK_API_RFC.md` in the moris repo).

## Compile and run

With PyMORIS (recommended):

    moris-run {name}.cpp --run-moris

Or in-tree:

    cd <moris>/build_opt && ninja moris
    <moris>/share/scripts/create_shared_object.sh . build_opt {name}
    mpirun -n 1 <moris>/build_opt/bin/moris {name}.so

## Where to edit

- Geometry / design variables: the GEN section (`tGen`)
- Physics / BCs: the FEM preset config (`tElasticity`) and the raw IQI blocks
- Objective / constraints: `aDeck.objective(...)` / `aDeck.constraint(...)`
- Solver: the SOL section (`tSol`)

Search for `TODO(user)` markers.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Scaffold a Deck API v2 MORIS input deck")
    parser.add_argument("name", help="Deck name (used for the file, .so, and output names)")
    parser.add_argument("--dir", default=None, help="Target directory (default: ./<name>)")
    parser.add_argument("--force", action="store_true", help="Overwrite existing files")
    args = parser.parse_args()

    if not args.name.isidentifier():
        parser.error(f"deck name '{args.name}' must be a valid identifier (letters, digits, underscores)")

    target = Path(args.dir) if args.dir else Path.cwd() / args.name
    target.mkdir(parents=True, exist_ok=True)

    deck_path = target / f"{args.name}.cpp"
    readme_path = target / "README.md"

    for path in (deck_path, readme_path):
        if path.exists() and not args.force:
            print(f"error: {path} exists (use --force to overwrite)", file=sys.stderr)
            return 1

    deck_path.write_text(DECK_TEMPLATE.replace("{name}", args.name))
    readme_path.write_text(README_TEMPLATE.replace("{name}", args.name))

    print(f"created {deck_path}")
    print(f"created {readme_path}")
    print(f"next:   moris-run {deck_path} --run-moris")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
