name: Run CTests on Custom Machine

on:
  push:
    branches:
      - main

jobs:
  dbg-build-and-test:
    runs-on: [self-hosted, Linux, X64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure project
      run: source ~/.bashrc_moris && export MORISROOT=`pwd` && cmake -S . -B build_dbg -DBUILD_ALL=ON -DMORIS_HAVE_DEBUG=ON -DMORIS_HAVE_SYMBOLIC=ON -DMORIS_HAVE_SYMBOLIC_STRONG=ON -DMORIS_USE_EXAMPLES=ON

    - name: Build project
      run:  source ~/.bashrc_moris && export MORISROOT=`pwd` && cmake --build build_dbg --parallel 9

    - name: Run tests
      run:  source ~/.bashrc_moris && export MORISROOT=`pwd` && cd build_dbg && ctest --output-on-failure
  
  opt-build-and-test:
    runs-on: [self-hosted, Linux, X64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure project
      run:  source ~/.bashrc_moris && export MORISROOT=`pwd` && cmake -S . -B build_opt -DBUILD_ALL=ON -DMORIS_USE_EXAMPLES=ON

    - name: Build project
      run:  source ~/.bashrc_moris && export MORISROOT=`pwd` && cmake --build build_opt --parallel 6

    - name: Run tests
      run:  source ~/.bashrc_moris && export MORISROOT=`pwd` && cd build_opt && ctest --output-on-failure
